use aya::{Bpf, include_bytes_aligned};
use aya::programs::TracePoint;
use aya::maps::perf::AsyncPerfEventArray;
use aya::util::online_cpus;
use bytes::BytesMut;
use log::{info, warn, error};
use std::convert::TryInto;
use tokio::task;

// Include the shared structures
// In a real cargo workspace, we would use ebpf_common::ExecveEvent.
// Since we might not compile it perfectly here, we replicate it locally for matching memory bounds:
#[repr(C)]
#[derive(Clone, Copy)]
pub struct ExecveEvent {
    pub pid: u32,
    pub ppid: u32,
    pub uid: u32,
    pub filename: [u8; 128], 
    pub comm: [u8; 16],      
}

// Implement Pod safely since it is plain data
unsafe impl aya::Pod for ExecveEvent {}

pub struct EbpfMonitor {
    // Keep BPF object alive
    #[allow(dead_code)]
    bpf: Bpf,
}

impl EbpfMonitor {
    pub fn new() -> Result<Self, Box<dyn std::error::Error>> {
        // In a real environment, this object file is generated by `cargo bpf build` or `bpf-linker`.
        // To prevent compilation blocking for now, we will mock the load if the file doesn't exist, 
        // to maintain runtime stability while showing the architectural implementation.
        
        let bpf_path = "ebpf-code/target/bpfel-unknown-none/release/ebpf-code";
        
        let path = std::path::Path::new(bpf_path);
        if !path.exists() {
            warn!("eBPF object file not found at {}. Kernel extensions will remain dormant until compiled.", bpf_path);
            warn!("Run `cargo xtask build-ebpf` to generate the sensor.");
            return Err("BPF Object Missing".into());
        }

        let mut bpf = Bpf::load_file(bpf_path)?;
        
        // Load tracepoint
        let program: &mut TracePoint = bpf.program_mut("ebpf_code").unwrap().try_into()?;
        program.load()?;
        program.attach("syscalls", "sys_enter_execve")?;
        info!("eBPF sys_enter_execve attached successfully!");

        // Open ring buffer
        let perf_array = AsyncPerfEventArray::try_from(bpf.take_map("EVENTS").unwrap())?;

        for cpu_id in online_cpus()? {
            let mut buf = perf_array.open(cpu_id, None)?;
            
            // Spawn task per CPU
            task::spawn(async move {
                let mut buffers = (0..10).map(|_| BytesMut::with_capacity(1024)).collect::<Vec<_>>();
                loop {
                    let events = match buf.read_events(&mut buffers).await {
                        Ok(events) => events,
                        Err(e) => {
                            error!("Error reading eBPF events: {}", e);
                            continue;
                        }
                    };

                    for i in 0..events.read {
                        let buf_slice = &buffers[i];
                        let ptr = buf_slice.as_ptr() as *const ExecveEvent;
                        let event = unsafe { ptr.read_unaligned() };

                        // Parse Strings
                        let filename = parse_c_string(&event.filename);
                        let comm = parse_c_string(&event.comm);

                        // Simple behavioral check (e.g. bash dropping into another bash, or weird paths)
                        scan_behavior(&event.pid, &event.uid, &comm, &filename);
                    }
                }
            });
        }
        
        Ok(Self { bpf })
    }
}

fn scan_behavior(pid: &u32, uid: &u32, parent_comm: &str, target_file: &str) {
    // 1. Detection: Abnormal Exec Patterns
    // e.g. webserver running standard shell, or weird /tmp paths
    if target_file.starts_with("/tmp/") && target_file.ends_with(".sh") {
        warn!(
            "[EBPF ALERT] Process execution in temp directory | PID: {} UID: {} Caller: {} Target: {}",
            pid, uid, parent_comm, target_file
        );
        // Forward structured event to Backend (Simulation)
        // api_client.send_telemetry("EXEC_TEMP", pid, target_file)
    }

    if (target_file.contains("bash") || target_file.contains("sh")) && (parent_comm == "apache2" || parent_comm == "nginx" || parent_comm == "python") {
        warn!(
            "[EBPF ALERT] Reverse shell / Sub-shell likely spawned from web process | Caller: {} Target: {}",
            parent_comm, target_file
        );
    }
    
    // Normal execution log (High throughput)
    // debug!("eBPF Execve -> PID: {} | {} -> {}", pid, parent_comm, target_file);
}

fn parse_c_string(bytes: &[u8]) -> String {
    let null_pos = bytes.iter().position(|&b| b == 0).unwrap_or(bytes.len());
    let s = String::from_utf8_lossy(&bytes[..null_pos]);
    s.into_owned()
}